set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ',xterm-256color:Tc'
set-option -ga terminal-overrides ',xterm-256color:RGB,tmux-256color:RGB'

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set -g mouse off

set-option -g focus-events on
set-option -g status-justify "left"
set-option -g status on
set-option -g status-interval 1

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi "v" send -X begin-selection
bind-key -T copy-mode-vi "y" send -X copy-selection

set -g @plugin "tmux-plugins/tpm"

set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin "joshmedeski/tmux-nerd-font-window-name"
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark'

set -g @tmux-gruvbox-left-status-a '#S'
set -g @tmux-gruvbox-right-status-y '%I:%M %p' # 09:54 PM
set -g @tmux-gruvbox-right-status-x '%m/%d/%Y'

set -g @tmux-gruvbox-right-status-z '#h #{tmux_mode_indicator}'

run "~/.tmux/plugins/tpm/tpm"
